services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - ./sidequest_backend/.env
    environment:
      # These should be defined in ./siderequest_backend/.env
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: plans_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./sidequest_backend
      dockerfile: Dockerfile
    environment:
      APPLY_MIGRATIONS: true
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./sidequest_backend/.env
    volumes:
      - ./sidequest_backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
